// Code generated by 'go generate'; DO NOT EDIT.

package BlockOpenHandle

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modAdvapi32 = windows.NewLazySystemDLL("Advapi32.dll")

	procConvertStringSecurityDescriptorToSecurityDescriptorW = modAdvapi32.NewProc("ConvertStringSecurityDescriptorToSecurityDescriptorW")
)

func ConvertStringSecurityDescriptorToSecurityDescriptorW(p1 uintptr, p2 uintptr, p3 uintptr, p4 uintptr) (p5 error) {
	r0, _, _ := syscall.Syscall6(procConvertStringSecurityDescriptorToSecurityDescriptorW.Addr(), 4, uintptr(p1), uintptr(p2), uintptr(p3), uintptr(p4), 0, 0)
	if r0 != 0 {
		p5 = syscall.Errno(r0)
	}
	return
}
